name: Deploy

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        yarn install
    - name: Eslinter code style test
      run: |
        node_modules/eslint/bin/eslint.js .

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: npm run build
